### ISSUE TITLE
Some dead individuals are marked as living

### ISSUE THREAD

**Issue by hartenthaler** [squatteur/webtrees-branch-statistics#1]
I found some persons that are counted as "living", but they are dead (see [here](https://ahnen.hartenthaler.eu/index.php?route=%2Ftree%2Fahnen%2Fwebtrees-branch-statistics%2FI591-6#)). There INDI-record contains code like:
```
1 DEAT
2 SOUR @S723@
2 AGE 55y
```
![Screenshot (83)](https://user-images.githubusercontent.com/6324175/103482886-c8666200-4de3-11eb-8432-5199f535a109.png)

**Comment by squatteur** [comment]
I think the INDI-record must be like this : 
1 DEAT **Y**

Maybe...

**Comment by hartenthaler** [comment]
No, 1 DEAT Y is only allowed if there are no subsequent records at level 2. If there are records at level 2, then only 1 DEAT is allowed.

**Comment by hartenthaler** [comment]
I just noticed that these four dead persons are marked by webtrees as "confidential" when I look at my site as a visitor. This seems to be an error in webtrees.
![Screenshot (88)](https://user-images.githubusercontent.com/6324175/103492760-574b9c80-4e2d-11eb-85d3-9492113f0efa.png)
I added now "1 RESN none" records to these 4 individuals, so they are now visible for visitors. But as expected this doesn't change the error that your module reports these persons as "living".

**Comment by squatteur** [comment]
I use the following function in webtrees/app/Individual.php : 

      / **
      * Calculate whether this individual is living or dead.
      * If not known to be dead, then assume living.
      *
      * @return bool
      * /
     public function isDead (): bool

This function return if a individual is dead or not.
it's difficult to redo a function without making a mistake and thinking about all the impacts.
Maybe there is a better function.

**Comment by squatteur** [comment]
The isDead() function is here:
[https://github.com/fisharebest/webtrees/blob/master/app/Individual.php](https://github.com/fisharebest/webtrees/blob/master/app/Individual.php)

You can check if there is a problem. I don't know.

**Comment by fisharebest** [comment]
> I use the following function in webtrees/app/Individual.php

This is the correct function.

**Comment by hartenthaler** [comment]
All the experts agree that GEDCOM standard says: You have to use 1 DEAT Y if there is no DATE or PLAC below. So you are right that I have to use 1 DEAT Y in my records. I changed them and now isDead() says that they are dead. So we can close this issue.
