### ISSUE TITLE
PHP error in webtrees 2.1 beta 2

### ISSUE THREAD

**Issue by Jefferson49** [squatteur/webtrees-branch-statistics#11]
Used within webtrees 2.1 beta 2, webtrees-branch-statistics throws a PHP error, see attachement.

[PHP error webtrees-branch-statistics in 2.1 beta 2.txt](https://github.com/squatteur/webtrees-branch-statistics/files/8499379/PHP.error.webtrees-branch-statistics.in.2.1.beta.2.txt)

**Comment by squatteur** [comment]
Hi Jefferson49, I will answer you this week.
Thank you for this issue.
