### ISSUE TITLE
Meaning of "total births"

### ISSUE THREAD

**Issue by hartenthaler** [squatteur/webtrees-branch-statistics#2]
The last entry in the summary is "Total births". What is the meaning? Total number of found persons? That would make sense. Total number of birth/baptism records? Then this number is wrong in my example (see [here](https://ahnen.hartenthaler.eu/index.php?route=%2Ftree%2Fahnen%2Fwebtrees-branch-statistics%2FI591-6#)), because these persons do not have either birth nor baptism records.
![Screenshot (84)](https://user-images.githubusercontent.com/6324175/103483106-64449d80-4de5-11eb-9e34-e8e3455157c0.png)

**Comment by squatteur** [comment]
"Total births" means the total of individuals with the INDI record: 1 BIRTH Y
"Total death" means the total of individuals with the INDI record: 1 DEAT Y
This makes it possible to check that an even empty recording (without date or source) is indeed present.
The only interest is the verification to have these empty records registered. 
I can delete the column.

**Comment by hartenthaler** [comment]
In my example some of the 7 persons do not have a 1 BIRT record. But if a person exists (INDI record exists) you can always assume that this person was born, even if there is no BIRT record. So I would prefer if you delete the last column in this table.

**Comment by squatteur** [comment]
Last column is deleted.
