### ISSUE TITLE
Design of summary table could be better

### ISSUE THREAD

**Issue by hartenthaler** [squatteur/webtrees-branch-statistics#3]
![Screenshot (85)](https://user-images.githubusercontent.com/6324175/103483193-dddc8b80-4de5-11eb-8680-77051a737d06.png)
This table is not very clear.
- I think it is not necessary to use "Total" (in German: "Anzahl"). Maybe you can use "Male" instead of "Total male". This makes this table shorter.
- Because there are no borderlines, it is not clear which number belongs to which header. Maybe you can use border lines and/or center the number under their heading.
- The meaning of "complete" is not clear. You explained it in your email to me. Maybe you can add this information in a second table with the following headings: "birth/baptism records", "marriage records", "death/burial records", "complete = number of persons with all these three types of records".

**Comment by squatteur** [comment]
I added borderlines, it's clearer.
- "Male" instead of "Total male"
- add this information : "Complete" means an individual with a media for birth or baptism, marriage and death.
