### ISSUE TITLE
Design of table "Total living"

### ISSUE THREAD

**Issue by hartenthaler** [squatteur/webtrees-branch-statistics#4]
- The head "Total living" should be bold. Then the ":" can be eliminated.
- It would be nice if there are links (URLs) behind these persons. Because it would be nice if it is possible to check why they are marked as living by following this link.

![Screenshot (87)](https://user-images.githubusercontent.com/6324175/103483509-01a0d100-4de8-11eb-9b89-19f51c530bbe.png)

**Comment by squatteur** [comment]
I'm doing a new tag today with this issue
