### ISSUE TITLE
Numbering of Generations

### ISSUE THREAD

**Issue by hartenthaler** [squatteur/webtrees-branch-statistics#5]
You start with generation 1 for the person itself, the proband. I normally start with generation 0, and the parents are then generation 1. But some people use roman numbering and they start therefore as you with I for the person and II for the parents. So this is maybe also possible.
It would be perfect if this could be defined by the admin, but then your module needs an interface for the control panel of webtrees.

**Comment by squatteur** [comment]
I put from 0 then we will see for an administration panel.
