### ISSUE TITLE
German Translation

### ISSUE THREAD

**Issue by hartenthaler** [squatteur/webtrees-branch-statistics#6]
First: it looks really great now! Thanks a lot!

Some minor remarks mainly regarding translation to German:
![Screenshot (111)_LI](https://user-images.githubusercontent.com/6324175/103579153-12307480-4ed8-11eb-8c04-3ab32712708e.jpg)

- Generation: I thought that you planned to start with 0
- Personen: what is the meaning of the colors in this column? green >= 50%, yellow ?, red < 10%? Is the color necessary? Why these values, why not "green = 100% red <100%"?
- Kumulierte Personenanzahl: it is not necessary to have "Personen" in each line, because this word is already in the heading
- Lebenszeit
- Vorfahren: "selbst" is ok, but "Proband" would be better; "Großelternteil" is ok, but "Großeltern" would be more consistent to "Eltern"; "Urgroßvater/-mutter" is ok, but again not consistent to previous generations: "Urgroßeltern" would be better; the following generations are not correct named (in English and in German: instead of x4 it should be x2): see [German](https://de.wikipedia.org/wiki/Generationsbezeichnungen)
- ...
- Vollständige/vorhandene Personen: explanation "Complete means ..." can be translated to German like "Vollständig" bedeutet, dass für eine Person Medien für Geburt/Taufe, Heirat und Tod/Beerdigung vorliegen
- "männliche": to be consistent with Lebend/Verstorben it should be "Männlich" (singular and capital first letter)
- "weibliche" should be "Weiblich"
- ...
- "Total Living"/"Anzahl Lebende" should be "Living Persons" or just "Living" because it is a list and not "total"; in German: "Lebende Personen"
- the links behind the persons are great, but now the (XREF) behind the names is doubled; this is new function of the custom Vesta module, which adds the XREF behind all names; maybe this function is now called two times - I will ask the programmer of this Vesta module to check if there is already a (XREF) behind a name before he adds a new (XREF).

**Comment by squatteur** [comment]
Thank you very much for the time spent writing this message. 
Here is what I corrected :

- Generation: Now, I start with 0
- Personen: The colors were chosen arbitrarily. I change the thresholds as you propose, it makes more sense
- Kumulierte Personenanzahl: Personen is removed
- Lebenszeit and Vorfahren: translate is good
- Vollständige/vorhandene Personen: Thank you for the translated sentence
- "männliche"and "weibliche" : now it's good

- "Total Living"/"Anzahl Lebende" : I corrected this column title
- Double (XREF): the module tests if there is an (XREF) to see if it should add it.

In French : Generationsbezeichnungen
[https://fr.wikipedia.org/wiki/Liste_d'ascendance](https://fr.wikipedia.org/wiki/Liste_d%27ascendance)
the comparison between languages is difficult.
Thanks for your help.

**Comment by hartenthaler** [comment]
Great! A really nice module with helpful additional information! My last comments:

For English I would prefer some plural "s":
![Screenshot (132)_LI](https://user-images.githubusercontent.com/6324175/105644801-cc901780-5e97-11eb-8257-4c9fa2abf53c.jpg)

For German I have the following remarks:
- instead of "Personen" it should be singular "Person"
- instead of "Generation" it should be plural "Generationen"
- in the second column you should delete "Kumulierte"
![Screenshot (133)_LI](https://user-images.githubusercontent.com/6324175/105644823-f6493e80-5e97-11eb-99ab-feb57a434c6e.jpg)

**Comment by squatteur** [comment]
Es ist klar. Danke.
Fixed. The progress bar has gone from 3 colors to 1, is it good for you?

**Comment by hartenthaler** [comment]
Yes! This looks clear and has the same information as before.
