### ISSUE TITLE
assert statement in ./src/Module.php throws a "assert($tree instanceof Tree) failed" error

### ISSUE THREAD

**Issue by reteP-riS** [squatteur/webtrees-branch-statistics#9]
I installed webtrees-branch-statistics-1.0.2 on webtrees 2.0.13 and when calling the branch statistics diagram the assert statement in [line 155](https://github.com/squatteur/webtrees-branch-statistics/blob/c3c4417c52386828a4f00a3481cba42df6c82c31/src/Module.php#L155) of ./src/Module.php throws this "assert($tree instanceof Tree) failed" error.

[assert-error.txt](https://github.com/squatteur/webtrees-branch-statistics/files/6189585/assert-error.txt)

The php manual says "Assertions should be used as a debugging feature only." So I removed that line and - voilà - the module works as expected, but there are more assert statements in this file and maybe in other files as well.

I'd therefore like to suggest a code review regarding these assert statements.

**Comment by squatteur** [comment]
Thanks for the explanation. Normally it's ok now.
